// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkmGzDpoHyLAhvIyqFTaNTAhtTI7XUags',
    appId: '1:906412990303:web:82c31336f4db3e203320ea',
    messagingSenderId: '906412990303',
    projectId: 'solutionchallenge-c03da',
    authDomain: 'solutionchallenge-c03da.firebaseapp.com',
    storageBucket: 'solutionchallenge-c03da.firebasestorage.app',
    measurementId: 'G-TQ7QK3SW0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO5OiQjltf740krNY-i27-EZY5ExymHfs',
    appId: '1:906412990303:android:5b6abe17cd7cbbd63320ea',
    messagingSenderId: '906412990303',
    projectId: 'solutionchallenge-c03da',
    storageBucket: 'solutionchallenge-c03da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwmNhpkH5uFm4XhUDSF-31ELVxLn21fBw',
    appId: '1:906412990303:ios:bab6868f30304ddd3320ea',
    messagingSenderId: '906412990303',
    projectId: 'solutionchallenge-c03da',
    storageBucket: 'solutionchallenge-c03da.firebasestorage.app',
    iosBundleId: 'com.example.newSolarc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwmNhpkH5uFm4XhUDSF-31ELVxLn21fBw',
    appId: '1:906412990303:ios:bab6868f30304ddd3320ea',
    messagingSenderId: '906412990303',
    projectId: 'solutionchallenge-c03da',
    storageBucket: 'solutionchallenge-c03da.firebasestorage.app',
    iosBundleId: 'com.example.newSolarc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkmGzDpoHyLAhvIyqFTaNTAhtTI7XUags',
    appId: '1:906412990303:web:977e42ef991d4f733320ea',
    messagingSenderId: '906412990303',
    projectId: 'solutionchallenge-c03da',
    authDomain: 'solutionchallenge-c03da.firebaseapp.com',
    storageBucket: 'solutionchallenge-c03da.firebasestorage.app',
    measurementId: 'G-0Q38KG3N38',
  );

}